export const LOAD_QUIZ_REQUEST = "LOAD_QUIZ_REQUEST";
export const LOAD_QUIZ_SUCCESS = "LOAD_QUIZ_SUCCESS";
export const LOAD_QUIZ_FAIL = "LOAD_QUIZ_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

