export const SUBMIT_RESULT_REQUEST = "SUBMIT_RESULT_REQUEST";
export const SUBMIT_RESULT_SUCCESS = "SUBMIT_RESULT_SUCCESS";
export const SUBMIT_RESULT_FAIL = "SUBMIT_RESULT_FAIL";
export const ALL_RESULT_REQUEST = "ALL_RESULT_REQUEST";
export const ALL_RESULT_SUCCESS = "ALL_RESULT_SUCCESS";
export const ALL_RESULT_FAIL = "ALL_RESULT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

